# Generated by Django 2.1.1 on 2018-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20181008_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewscount',
            options={'ordering': ['-time_stamp'], 'verbose_name': 'Object viewed', 'verbose_name_plural': 'Object viewed'},
        ),
        migrations.AddField(
            model_name='viewscount',
            name='ip_address',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='viewscount',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
