# Generated by Django 2.1.1 on 2018-10-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20181008_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewscount',
            options={'ordering': ['-time_stamp']},
        ),
    ]
