# Generated by Django 2.1.1 on 2018-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20181008_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewscount',
            name='address',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
