# Generated by Django 2.1.1 on 2018-10-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_registercount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registercount',
            name='product',
        ),
        migrations.RemoveField(
            model_name='registercount',
            name='user',
        ),
    ]
