# Generated by Django 2.1.1 on 2018-09-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='Limited (12 months)', max_length=100),
        ),
    ]
