# Generated by Django 2.1.1 on 2018-09-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.TextField(default='Free delivery available in South Africa only'),
        ),
    ]
