# Generated by Django 2.1.1 on 2018-10-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slogan',
            field=models.CharField(default='Hot items, Affordable prices', max_length=150),
        ),
    ]
