# Generated by Django 2.1.1 on 2018-10-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addBanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='addBanner/%Y/%m/%d')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='addBanner.AddBanner')),
            ],
        ),
    ]
