# Generated by Django 2.1.1 on 2018-10-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addBanner', '0002_addbannerimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbannerimage',
            old_name='image',
            new_name='imageMore',
        ),
    ]
