# Generated by Django 2.1.1 on 2018-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addBanner', '0003_auto_20181029_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbanner',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
