# Generated by Django 2.1.1 on 2018-10-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_producturl'),
        ('addBanner', '0005_auto_20181029_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbanner',
            name='product',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
