# Generated by Django 2.1.1 on 2018-11-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addBanner', '0009_auto_20181030_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbanner',
            name='add_is_active',
            field=models.CharField(choices=[('AC', 'Active'), ('NO', 'Not Active')], default='AC', max_length=2),
        ),
    ]
