# Generated by Django 2.1.1 on 2018-11-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addBanner', '0010_addbanner_add_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbanner',
            name='add_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
