# Generated by Django 2.1.1 on 2018-10-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'Payment received'), ('PO', 'Processing order'), ('ID', 'Items dispatched'), ('IR', 'Items received')], default='Payment Received', max_length=2),
        ),
    ]
