# Generated by Django 2.1.1 on 2018-10-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('EP', 'EFT Payment'), ('DP', 'Payment on delivery')], default='Pay on delivery', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PP', 'Processing payment'), ('PR', 'Payment received'), ('PO', 'Processing order'), ('ID', 'Items dispatched'), ('IR', 'Items received')], default='Processing payment', max_length=2),
        ),
    ]
