# Generated by Django 2.1.1 on 2018-10-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_barcode'),
        ('orders', '0003_auto_20181003_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='productImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_images', to='shop.ProductImage'),
        ),
    ]
