# Generated by Django 2.1.1 on 2018-10-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='productImage',
        ),
    ]
