# Generated by Django 2.1.1 on 2018-10-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('FD', 'Free delivery (Free) - 20 to 37 days'), ('PL', 'Priority delivery (R 99.00) - 4 to 15 days')], default='Free delivery - 20 to 37 days', max_length=2),
        ),
    ]
