# Generated by Django 2.1.1 on 2018-10-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181010_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing_payment', 'Processing payment'), ('payment_received', 'Payment received'), ('processing_order', 'Processing order'), ('items_dispatched', 'Items dispatched'), ('items_received', 'Items received')], default='Processing payment', max_length=120),
        ),
    ]
